---
title: "figsFromRonsIPM"
author: "Ben"
date: "March 19, 2015"
output: html_document
---

```{r libraries}
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r capitlize first letter}

capwords <- function(s, strict = FALSE) {
    cap <- function(s) paste(toupper(substring(s, 1, 1)),
                  {s <- substring(s, 2); if(strict) tolower(s) else s},
                             sep = "", collapse = " " )
    sapply(strsplit(s, split = " "), cap, USE.NAMES = !is.null(names(s)))
}

```


```{r color blind palette}
cbbPalette <- c("#000000", 
                #"#E69F00", "#56B4E9", "#009E73", "#F0E442", 
                "#0072B2", "#D55E00"
                #, "#CC79A7"
                )
```


```{r read data}

fig1 <- read.csv('Copy of Figure 1.csv',header=T)

#make long
f1 <- 
  select(fig1,-X) %>%
  gather(type,value,observed.length:equilibrium.N) %>%
  separate(type, c("type", "var")) %>%
  mutate( type = factor(type,levels=c('observed','predicted','equilibrium'),
                             labels=c('Observed','Predicted','Equilibrium'), ordered=T) ) 

################################
# Fig 4 Left
fig4 <- read.csv('Fig 4 left column.csv',header=T)
f4 <- select(fig4,-X) %>% 
      mutate( effect = ifelse(Type=='Direct','Climate',ifelse(Type=='Indirect','Density','Total')),
              year= iter + 2002,
              trait='N') 

# Fig 4 Center and Right
fig4CR <- read.csv('Fig 4 cen and right column.csv',header=T)
f4CRa <- select(fig4CR,-X) %>% 
         mutate( year= iter + 2002 ) 
# get totals
f4CRb <- f4CRa %>%         
         group_by( Env,River,iter,year ) %>%
         summarise( dNdt = sum( dNdt )) %>%
         mutate( wrtSeason = 'Total' )

f4CR <- bind_rows(f4CRa,f4CRb) %>%
    mutate( type = factor(wrtSeason,levels=c('Total','Autumn','Winter','Spring','Summer'), ordered=T),
            trait = 'N') 


################################
# Fig 6 Left
fig6 <- read.csv('Fig 6 left column.csv',header=T)
f6 <- select(fig6,-X) %>% 
      mutate( effect = ifelse(Type=='Direct','Climate',ifelse(Type=='Indirect','Density','Total')),
              year= iter + 2002,
              trait='length') 

# Fig 6 Center and Right
fig6CR <- read.csv('Fig 6 cen and right column.csv',header=T)
f6CRa <- select(fig6CR,-X) %>% 
         mutate( year= iter + 2002 ) 
# get totals
f6CRb <- f6CRa %>%         
         group_by( Env,River,iter,year ) %>%
         summarise( dNdt = sum( dNdt )) %>%
         mutate( wrtSeason = 'Total' )

f6CR <- bind_rows(f6CRa,f6CRb) %>%
    mutate( type = factor(wrtSeason,levels=c('Total','Autumn','Winter','Spring','Summer'), ordered=T),
            trait = 'Size') 


#put traits together
f46 <- bind_rows(f4,f6) %>%
       mutate( effect = factor(effect,levels=c('Total','Density','Climate'), ordered=T)) 

f46CR <- bind_rows(f4CR,f6CR)

```

```{r make trend figs}
popSizeWB <- 
  
filter(f1, river=='Westbrook' & var=='N') %>%
ggplot( aes(year,value,shape=type,linetype=type,color=type,size=type) ) +
  geom_point(size=5)+#, shape=16) +
  geom_line() +
  theme_bw(base_size=25) +
  theme(legend.justification=c(0,0), legend.position=c(.7,.83),
        legend.title=element_blank(),
        legend.text = element_text(size = 35)) +
  scale_x_continuous('Year',limits=c(2003,2012), breaks=c(seq(2002,2012,2))) +
  scale_y_continuous('Population size') +
  scale_shape_manual(values=c(16,1,NA)) +
  scale_linetype_manual(values=c(1,3,1)) +
 # scale_colour_manual(values=cbbPalette)+#c("red","blue",'black')) +
  scale_size_manual(values=c(1.,1,1.5)) +
  scale_color_hue(l=40)

ggsave( file=paste0(getwd(),'/popSizeWB.png'), plot=popSizeWB, dpi=600 , width=6,height=5, units='in', scale=2 )

###############
# size

lengthWB <- 
  
filter(f1, river=='Westbrook' & var=='length') %>%
ggplot( aes(year,value,shape=type,linetype=type,color=type,size=type) ) +
  geom_point(size=5)+#, shape=16) +
  geom_line() +
  theme_bw(base_size=25) +
  theme(legend.justification=c(0,0), legend.position=c(.1,.83),
        legend.title=element_blank(),
        legend.text = element_text(size = 35)) +
  scale_x_continuous('Year',limits=c(2003,2012), breaks=c(seq(2002,2012,2))) +
  scale_y_continuous('Mean body size') +
  scale_shape_manual(values=c(16,1,NA)) +
  scale_linetype_manual(values=c(1,3,1)) +
 # scale_colour_manual(values=cbbPalette)+#c("red","blue",'black')) +
  scale_size_manual(values=c(1.,1,1.5)) +
  scale_color_hue(l=40)

ggsave( file=paste0(getwd(),'/lengthWB.png'), plot=lengthWB, dpi=600 , width=6,height=5, units='in', scale=2 )

```

```{r mean sensitivity barplots}

# pop size average for climate and density
sensBarWBN <- 

f46 %>%
  filter(River=="Westbrook" & trait=='N') %>%
  group_by(trait,effect) %>%
  summarise( mean=mean(dNdt) ) %>%
  ggplot(aes(effect,mean,fill=effect)) +
    geom_bar(stat='identity') +
    theme_bw(base_size=25) +
    theme(legend.position='none') +
    scale_x_discrete('Pathway') +
    scale_y_continuous('Sensitivity of equilibrium population size') +
    geom_hline(yintercept=0, color='darkgrey') 

  ggsave( file=paste0(getwd(),'/sensBarWBN.png'), plot=sensBarWBN, dpi=600, width=6,height=5,units='in', scale=2 )

### all rivers
f46 %>%
  filter(trait=='N') %>%
  group_by(River,trait,effect) %>%
  summarise( mean=mean(dNdt) ) %>%
  ggplot(aes(effect,mean,fill=River)) +
    geom_bar(position=position_dodge(),stat='identity') +
    theme_bw(base_size=25) +
  #  theme(legend.position='none') +
    scale_x_discrete('Pathway') +
    scale_y_continuous('Sensitivity of equilibrium population size') +
    geom_hline(yintercept=0, color='darkgrey') 

##########################
# pop size by season
sensBarSeasonWBN <- 

f46CR %>%
  filter(River=="Westbrook" & trait=='N') %>%
  group_by(trait,type,Env) %>%
  summarise( mean=mean(dNdt) ) %>%
  ggplot(aes(type,mean,fill=type)) +
    geom_bar(stat='identity') +
    theme_bw(base_size=25) +
    theme(legend.position='none') +
    scale_x_discrete('Pathway') +
    scale_y_continuous('Sensitivity of equilibrium population size') +
    geom_vline(xintercept=1.513) +
    geom_hline(yintercept=0, color='darkgrey') +
    facet_wrap(~Env)

  ggsave( file=paste0(getwd(),'/sensBarSeasonWBN.png'), plot=sensBarSeasonWBN, dpi=600, width=6,height=5,units='in', scale=2 )

###############################################
# body size average for climate and density
sensBarWBSize <- 

f46 %>%
  filter(River=="Westbrook" & trait=='length') %>%
  group_by(trait,effect) %>%
  summarise( mean=mean(dNdt) ) %>%
  ggplot(aes(effect,mean,fill=effect)) +
    geom_bar(stat='identity') +
    theme_bw(base_size=25) +
    theme(legend.position='none') +
    scale_x_discrete('Pathway') +
    scale_y_continuous('Sensitivity of equilibrium body size') +
    geom_hline(yintercept=0, color='darkgrey')

  ggsave( file=paste0(getwd(),'/sensBarWBSize.png'), plot=sensBarWBSize, dpi=600, width=6,height=5,units='in', scale=2 )

### all rivers
f46 %>%
  filter(trait=='length') %>%
  group_by(River,trait,effect) %>%
  summarise( mean=mean(dNdt) ) %>%
  ggplot(aes(effect,mean,fill=River)) +
    geom_bar(position=position_dodge(),stat='identity') +
    theme_bw(base_size=25) +
  #  theme(legend.position='none') +
    scale_x_discrete('Pathway') +
    scale_y_continuous('Sensitivity of equilibrium body size') +
    geom_hline(yintercept=0, color='darkgrey') 


# body size by season
sensBarSeasonWBSize <- 

f46CR %>%
  filter(River=="Westbrook" & trait=='Size') %>%
  group_by(trait,type,Env) %>%
  summarise( mean=mean(dNdt) ) %>%
  ggplot(aes(type,mean,fill=type)) +
    geom_bar(stat='identity') +
    theme_bw(base_size=25) +
    theme(legend.position='none') +
    scale_x_discrete('Pathway') +
    scale_y_continuous('Sensitivity of equilibrium body size') +
    geom_vline(xintercept=1.513) +
    geom_hline(yintercept=0, color='darkgrey') +
    facet_wrap(~Env)

  ggsave( file=paste0(getwd(),'/sensBarSeasonWBSize.png'), plot=sensBarSeasonWBSize, dpi=600, width=6,height=5,units='in', scale=2 )

```

```{r climate and density sensitivity graphs}
###################
# Sensitivities

# PopSize

ggSens <- function(d,riv,t){
  
  label <- 'population'; if(t=='Size') label <- 'body' 
  
  gg <- 
  filter(d, River==riv & trait == t ) %>%
  ggplot( aes( year,dNdt,linetype=effect,color=effect ) ) +
  #geom_point(size=5)+#, shape=16) +
    geom_line(size=1.5) +
    theme_bw(base_size=25) +
    theme(legend.justification=c(0,0), legend.position=c(0.7,0.7),
          legend.title=element_blank(),
          legend.text = element_text(size = 35)) +
    scale_x_continuous('Year',limits=c(2003,2012), breaks=c(seq(2002,2012,2))) +
    scale_y_continuous(paste0('Sensitivity of equilibrium ',label,' size')) +
    scale_linetype_manual(values=c(3,2,1)) +
    scale_color_hue(l=40) +
    geom_hline(yintercept=0)

  ggsave( file=paste0(getwd(),'/sens',t,riv,'.png'), plot=gg, dpi=600, width=6,height=5,units='in', scale=2 )
  return(gg)
} 

gN <- ggSens(f46,'Westbrook','N')
gLength <- ggSens(f46,'Westbrook','length')

```

``` {r flow and temperature sensitivity graphs}
###################
# Flow

sensPopSizeF_WB <- 

  
ggSensFT <- function(d,riv,t,e){ 
 
label <- 'population'; if(t=='Size') label <- 'body'  

gg <-     
filter(d, River==riv & trait==t, Env == e ) %>%
ggplot( aes( year,dNdt,linetype=type,color=type ) ) +
  #geom_point(size=5)+#, shape=16) +
  geom_line(size=1.5) +
  theme_bw(base_size=25) +
  theme(legend.justification=c(0,0), legend.position=c(0.7,0.3),
        legend.title=element_blank(),
        legend.text = element_text(size = 35)) +
  scale_x_continuous('Year',limits=c(2003,2012), breaks=c(seq(2002,2012,2))) +
  scale_y_continuous(paste0('Sensitivity of equilibrium ',label,' size')) +
  scale_linetype_manual(values=c(1,2,3,4,5)) +
 # scale_colour_manual(values=cbbPalette)+#c("red","blue",'black')) +
  scale_color_hue(l=40) +
  geom_hline(yintercept=0)

ggsave( file=paste0(getwd(),'/sens',t,e,riv,'.png'), plot=gg, dpi=600 , width=6,height=5, units='in', scale=2 )

return(gg)
}

gNF <- ggSensFT(f46CR,'Westbrook','N','Flow')
gNT <- ggSensFT(f46CR,'Westbrook','N','Temp')
gLF <- ggSensFT(f46CR,'Westbrook','Size','Flow')
gLT <- ggSensFT(f46CR,'Westbrook','Size','Temp')

```


```{r env data}
load('D:/PITTAGMAIN/CMR Analyses/Hierach_Bugs/allSpp/dMDataOutBKT2002_2012.RData')
dMData$riverOrdered <- factor(dMData$river,levels=c('WEST BROOK','WB JIMMY','WB MITCHELL','WB OBEAR'), ordered=T)

m <- dMData %>%
       group_by(riverOrdered,riverN,season,year) %>%
       summarise(Temperature = mean(fullMeanT, na.rm=TRUE),
                 Flow = mean(fullMeanD, na.rm=TRUE),
                 n=n()) 

rm(dMData)

seasonLabeller <- function(var, value){
  value <- as.character(value)
  if (var=="season") { 
    value[value=="1"] <- "Spring"
    value[value=="2"] <- "Summer"
    value[value=="3"] <- "Autumn"
    value[value=="4"] <- "Winter"
  }
  return(value)
}
m$seasonText <- seasonLabeller('season',m$season)
m$seasonText <- factor(m$seasonText,levels=c("Autumn","Winter","Spring","Summer"), ordered=T)

mL <- gather(m,flowTemp,var,Temperature:Flow)

fT <- 

ggplot(filter(mL,riverOrdered == 'WEST BROOK'), aes(year,var)) +
  geom_point(size=4) +
  geom_smooth(color='black',method=lm, se=F) +
  theme_bw(base_size=25) +
  scale_x_continuous('Year',limits=c(2003,2012), breaks=c(seq(2002,2012,2))) +
  scale_y_continuous('') +
  facet_grid(flowTemp~seasonText,scales='free')

  ggsave( file=paste0(getwd(),'/flowTemperatureMeans.png'), plot=fT, dpi=600, width=10,height=5,units='in', scale=2 )

# all rivers
fTAll <- 

ggplot(filter(mL), aes(year,var,color=riverOrdered)) +
  geom_point(size=4) +
  geom_smooth(method=lm, se=F) +
  theme_bw(base_size=25) +
  scale_x_continuous('Year',limits=c(2003,2012), breaks=c(seq(2002,2012,2))) +
  scale_y_continuous('') +
  facet_grid(flowTemp~seasonText,scales='free')

  ggsave( file=paste0(getwd(),'/flowTemperatureMeansAll.png'), plot=fTAll, dpi=600, width=10,height=5,units='in', scale=2 )
```

